version: "3.7"
services:
  ui_service:
    container_name: categories_service
    build:
      context: .
      target: build
    volumes:
      - ./:/app/
      - /app/node_modules/
    ports:
      - 21223:21223
    restart: always
    environment:
      - PORT=21223
      - CONNECT_URL=mongodb://root:example@mongo:27017/categories?authMechanism=DEFAULT&authSource=admin
    command: npm run dev
